server:
  port: 5100

springdoc:
  api-docs:
    path: /t2c-api

  swagger-ui:
    path: t2c/ui
    oauth:
      use-basic-authentication-with-access-code-grant: true

  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
      enabled: true
